### ISSUE TITLE
[Refactor] WeeklyCalendarView 네비View/UI수정 및 ViewController 생성 함수구현 

### ISSUE THREAD

**Issue by dongjin97** [PlanLit/PomoHabit#113]
## 제목:
[Refactor] WeeklyCalendarView 네비View/UI수정 및 ViewController 생성 함수구현 

## 설명:
네비 View의 border이 View에 대한 offset 값 0이어야 됨 -> 오토레이아웃 및 제약조건 수정
ViewController 생성및 초기화를 팩토리 메소드로 구현 -> ViewContoller에 직접적인 접근을 막기위함
주간 달성율 0일 경우 분기처리
## TODO:

- [x] - 오토레이아웃및 제약조건 수정
- [x] - ViewController 생성 및 초기화 팩토리 메소드로 구현
- [x] - 진행상태가 0일경우의 분기처리
