### ISSUE TITLE
[Fix] 주간 캘린더 화면

### ISSUE THREAD

**Issue by dongjin97** [PlanLit/PomoHabit#119]
## 제목:
주간 캘린더 화면 테스트중 수정사항 발견

## 설명:
앱테스트중 수성사항 발생
1. 오늘 날짜에 대한 메모 설정 
2. 스크롤 불가능
3. 주간 달성률 뷰 수정으로인한 변경 사항적용

## TODO:

- [x] - Default로 오늘날짜 메모 설정
- [x] - 스크롤 안되는 이슈 수정
- [x] - 주간 달성률 뷰 수정으로인한 변경 사항적용
