### ISSUE TITLE
중간 발표후 CoreData 재설계

### ISSUE THREAD

**Issue by dongjin97** [PlanLit/PomoHabit#69]
## 제목:
중간 발표후 CoreData 재설계

## 설명:
날짜 관리 String 보다 Date가 효과적
###
상황
- 현재 Date를 String으로 변환후 CoreData에 저장 
- 저장된데이터를 불러와서 날짜를 가공하기 위하여 다시 Date로 바꿔줌
이유
1. Date에서 활용하는 함수를 사용하기 위해서는 Date Type이여야한다.
2. 단순히 String으로 바꾸어 저장하는 의미가 존재 하지 않음

## TODO:
- [x] - 1. User 엔터티 starTime: String-> alarmTime : Date
- [x] - 2., 21일 치 mock 데이터 생성
- [x] - 3. Timer 습관 완료후 오늘 날짜의 TotalHabitInfo MockData 수정
- [x] - 4. TotalHabitInfo 특정 날짜 정보 얻기
