### ISSUE TITLE
[Chore] 메모, whiteNoise 데이터 전달 관련

### ISSUE THREAD

**Issue by joonBaek12** [PlanLit/PomoHabit#83]
## TODO:

- [ ] 메모 모달 UI 레이아웃 이슈
- [ ] 메모 데이터 전달
- [ ] 화이트 노이즈 변경 기능
